In [1]:
import pandas as pd

In [ ]:
df = pd.read_csv("../../datasets/dataset_Facebook.csv",delimiter=";")

In [14]:
df.head()

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393

In [17]:
df["Type"].unique()

<StringArray>
['Photo', 'Status', 'Link', 'Video']
Length: 4, dtype: str

In [18]:
Photos = df[df["Type"]=="Photo"]

In [20]:
Photos.head()

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
6,139441,Photo,3,12,1,3,1.0,11692,19479,481,265,364,15432,9328,379,3,249.0,27.0,279

In [21]:
Statuses = df[df["Type"]=="Status"]

In [22]:
Links = df[df["Type"]=="Link"]
Videos = df[df["Type"]=="Video"]

In [23]:
merged = pd.concat([Links, Videos])

In [24]:
merged.head()

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
22,138414,Link,1,12,7,10,0.0,3454,6853,118,104,130,6282,3100,106,0,16.0,2.0,18
41,138895,Link,1,12,6,3,1.0,18480,28438,517,366,460,12078,6752,319,6,187.0,18.0,211
43,138353,Link,1,12,5,3,1.0,2645,4270,134,109,170,2330,1377,101,7,29.0,10.0,46
45,138353,Link,1,12,4,3,1.0,7968,13023,206,158,223,6734,3492,138,4,57.0,10.0,71
47,138353,Link,1,12,3,2,0.0,1925,3481,97,83,126,2307,1180,77,6,18.0,8.0,32

In [25]:
merged.sort_values(by="Page total likes")

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
492,85979,Link,1,1,5,11,0.0,45920,5808,753,655,763,15766,10720,220,0,128.0,9.0,137
481,86491,Link,1,1,4,4,1.0,4938,7910,66,63,70,6625,3804,59,0,5.0,2.0,7
485,86491,Link,1,1,2,2,0.0,5168,8371,66,59,71,7041,3996,58,0,12.0,2.0,14
477,86909,Link,1,1,6,4,0.0,39600,7927,572,496,581,12522,8176,167,1,101.0,5.0,107
470,91437,Link,1,2,3,13,0.0,9356,14986,448,381,505,13919,8460,392,4,114.0,13.0,131
438,98195,Link,2,3,6,6,0.0,5730,10083,103,71,97,8964,4830,92,2,32.0,15.0,49
430,100732,Link,1,3,7,14,0.0,2933,5144,24,23,26,3972,2012,19,0,6.0,0.0,6
425,102112,Link,3,3,1,3,0.0,6876,10885,282,245,337,9403,5752,259,2,68.0,15.0,85
408,106928,Link,1,4,6,4,0.0,34192,42092,338,322,389,22907,16464,230,1,36.0,7.0,44
403,107907,Link,1,4,2,6,0.0,70912,94172,1374,1106,1267,42338,27232,788,1,379.0,40.0,420
372,113028,Link,1,4,5,7,1.0,35360,45260,339,325,477,9105,5472,156,7,38.0,11.0,56
344,117764,Link,1,5,1,2,0.0,12540,19301,344,322,396,16914,11008,289,3,46.0,14.0,63
277,126424,Video,1,6,2,13,0.0,139008,277100,1779,1643,2356,107502,38720,1008,23,204.0,44.0,271
243,130791,Video,1,7,3,11,1.0,21872,40413,3872,3822,7327,24667,12920,2218,18,315.0,76.0,409
183,134879,Video,1,9,2,10,0.0,30624,56950,2080,1956,3253,32033,15744,1376,6,345.0,121.0,472
149,135713,Link,1,10,6,11,1.0,3616,6887,111,90,118,4263,2138,93,0,24.0,11.0,35
140,136013,Link,1,10,4,3,0.0,68992,229733,1032,975,1345,17842,8032,635,15,143.0,44.0,202
136,136393,Link,1,10,5,10,0.0,4664,9463,204,182,251,7196,3324,173,0,32.0,16.0,48
86,137177,Link,1,11,4,3,0.0,21176,54779,330,228,329,13858,5248,185,2,130.0,31.0,163
74,137893,Video,1,11,3,11,0.0,13544,30235,517,458,667,26622,11760,447,2,99.0,13.0,114
71,137893,Video,1,11,5,3,1.0,100768,220447,2101,1735,2331,59658,18880,885,17,449.0,84.0,550
55,138329,Video,1,11,6,2,1.0,16416,31950,459,411,539,21436,9568,363,2,65.0,14.0,81
45,138353,Link,1,12,4,3,1.0,7968,13023,206,158,223,6734,3492,138,4,57.0,10.0,71
43,138353,Link,1,12,5,3,1.0,2645,4270,134,109,170,2330,1377,101,7,29.0,10.0,46
49,138353,Link,1,12,2,2,0.0,1536,3094,84,76,99,2903,1407,76,1,12.0,1.0,14
47,138353,Link,1,12,3,2,0.0,1925,3481,97,83,126,2307,1180,77,6,18.0,8.0,32
22,138414,Link,1,12,7,10,0.0,3454,6853,118,104,130,6282,3100,106,0,16.0,2.0,18
41,138895,Link,1,12,6,3,1.0,18480,28438,517,366,460,12078,6752,319,6,187.0,18.0,211
29,138895,Video,1,12,4,11,1.0,36208,61262,1141,1068,1728,30131,14112,559,18,143.0,13.0,174

In [27]:
transposed = merged.T

In [28]:
transposed.head()

,22,41,43,45,47,49,86,136,140,149,...,481,485,492,29,55,71,74,183,243,277
Page total likes,138414,138895,138353,138353,138353,138353,137177,136393,136013,135713,...,86491,86491,85979,138895,138329,137893,137893,134879,130791,126424
Type,Link,Link,Link,Link,Link,Link,Link,Link,Link,Link,...,Link,Link,Link,Video,Video,Video,Video,Video,Video,Video
Category,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Post Month,12,12,12,12,12,12,11,10,10,10,...,1,1,1,12,11,11,11,9,7,6
Post Weekday,7,6,5,4,3,2,4,5,4,6,...,4,2,5,4,6,5,3,2,3,2

In [29]:
melted = pd.melt(merged,id_vars=['Type', 'Category'], value_vars=['like','share','comment'])

In [31]:
melted.head(100)

     Type  Category variable  value
0    Link         1     like   16.0
1    Link         1     like  187.0
2    Link         1     like   29.0
3    Link         1     like   57.0
4    Link         1     like   18.0
..    ...       ...      ...    ...
82  Video         1  comment   17.0
83  Video         1  comment    2.0
84  Video         1  comment    6.0
85  Video         1  comment   18.0
86  Video         1  comment   23.0

[87 rows x 4 columns]

In [33]:
wide = melted.pivot_table(
    index=['Type','Category'],
    columns='variable',
    values='value',
    aggfunc='sum'
)

In [35]:
wide.head(100)

variable        comment    like  share
Type  Category
Link  1            58.0  1513.0  254.0
      2             2.0    32.0   15.0
      3             2.0    68.0   15.0
Video 1            86.0  1620.0  365.0

In [37]:
melted1 = pd.melt(
    df,
    id_vars=['Type'],
    value_vars=['comment','like','share']
)

In [ ]:
melted1.tail(100)

       Type variable  value
1400  Photo    share   26.0
1401  Photo    share   38.0
1402  Photo    share   17.0
1403   Link    share   40.0
1404  Photo    share   24.0
...     ...      ...    ...
1495  Photo    share   26.0
1496  Photo    share   22.0
1497  Photo    share   18.0
1498  Photo    share   38.0
1499  Photo    share   28.0

[100 rows x 3 columns]

In [41]:
wide1 = melted1.pivot_table(index=['Type'],columns='variable',values='value',aggfunc='sum')

In [42]:
wide1.head()

variable  comment     like    share
Type
Link         62.0   1613.0    284.0
Photo      3192.0  77610.0  11461.0
Status      401.0   7952.0   1414.0
Video        86.0   1620.0    365.0